function T_HeadersIdx = s_parse_siemens_ECG_Header_KeyValPairs(T_HeadersIdx)
% Parse the information region (i.e. headers) in SIEMENS
% ideacmdtool-generated ECG data file. Transfrom them into key-value pairs
% and store it as a MATLAB table
% 
% Input:
%   Positional Arguments (Required):
%       T_HeadersIdx - a table contains the headers in ECG file and its
%                       location index in the 'first line data'. 
%       T_HeadersIdx could be generated by the function 
%                                   's_parse_siemens_ECG_Extract_Headers',
%       which is the second positional output argument.
% Output:
%   T_HeadersIdx - an updated table added a new column named InfoRegion,
%               which contains the splitted key-value pairs in a subtable.
%               In the subtable, column names are keys and elements in each
%               column are values.
%               The column 'content' in the input table will be removed.
% 
% By Kunru Song 2023.11.16


NoHeaders = height(T_HeadersIdx);
T_HeadersIdx.InfoRegion = repmat({table()}, NoHeaders, 1); % Initialize as a cell array of tables

for ihdr = 1:NoHeaders
    % Using regular expressions to match tokens
    tokens = regexp(T_HeadersIdx.Content{ihdr}, '(\w+)\s+([\d\.\s-]+)', 'tokens');

    % Transform the matched tokens into a struct
    tmpResult = struct();
    for i = 1:length(tokens)
        key = tokens{i}{1};
        value = str2num(tokens{i}{2}); %#ok<ST2NM> 
        tmpResult.(key) = value;
    end
    % Convert the struct to a table and store it in InfoRegion
    T_HeadersIdx.InfoRegion{ihdr} = struct2table(tmpResult);
end
T_HeadersIdx = removevars(T_HeadersIdx,"Content");